# Javascript Node CircleCI 2.0 configuration file
version: 2
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
var_1: &cache_npm npm-cache-v3
var_2: &ngcontainer
  docker:
    - image: sandangel/ngcontainer:latest

var_3: &set_bazel_options
  run: sudo cp .circleci/bazel.rc /etc/bazel.bazelrc
  run: chmod +x tools/bazel_stamp_vars.sh

jobs:
  bazel:
    <<: *ngcontainer
    steps:
      - checkout
      - restore_cache:
          key: *cache_npm

      - *set_bazel_options

      - run: bazel info release
      - run: bazel run :install --noshow_progress
      - run: npm run test:bazel

  build:
    <<: *ngcontainer
    steps:
      - checkout
      - restore_cache:
          key: *cache_npm

      - run: npm ci
      - run: npm run gulp ci:build

      - save_cache:
          key: *cache_npm
          paths:
            - ~/.npm

  lint:
    <<: *ngcontainer
    steps:
      - checkout
      - *set_bazel_options

      - restore_cache:
          key: *cache_npm

      - run: npm ci
      - run: npm run gulp ci:lint
      - run: if [ $CIRCLE_BRANCH == 'master' ]; then npm run validate:commit; else echo 'Not validate commit message.'; fi
      - run: 'buildifier -mode=check $(find . -type f \( -name BUILD.bazel -or -name BUILD \) ! -path "*/node_modules/*") || (echo "BUILD files not formatted. Please run ''yarn buildifier''" ; exit 1)'

  test:
    <<: *ngcontainer
    steps:
      - checkout
      - restore_cache:
          key: *cache_npm

      - run: npm ci
      - run: npm run gulp ci:test
      - run: npm run gulp ci:coverage

  deploy:
    <<: *ngcontainer
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          key: *cache_npm

      - run: npm -v
      - run: npm ci
      - run: npm run gulp ci:build
      - run: npm run gulp deploy

      - store_artifacts:
          path: dist/releases

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - bazel
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - test
            - lint
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - hold
          filters:
            branches:
              only: master
